version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - ./:/var/www
  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    ports:
      - "8086:80"
    depends_on:
      - php
